name: Lint HTML CSS JS

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install linters
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard eslint

      - name: Run HTMLHint
        run: htmlhint "**/*.html"

      - name: Run Stylelint
        run: stylelint "**/*.css"

      - name: Run ESLint
        run: eslint "**/*.js" || true
